import { useMemo } from 'react';
import type { VicData } from './types';

export const VIC_MOCK_DATA: VicData = {
  vehicle: {
    year: 2008,
    make: 'Ford',
    model: 'Crown Victoria Police Interceptor',
    shortName: 'Crown Vic P71',
    vin: '2FAHP71V28X142059',
    plate: 'WA / 847-TXQ',
    mileage: 184320,
    nextService: 187500,
    engine: '4.6L V8 SOHC',
    trans: '4R70W',
  },
  telemetry: {
    battery: 12.4,
    coolant: 198,
    oilPressure: 42,
    fuel: 0.62,
    rpm: 0,
    speed: 0,
    intake: 68,
    ambient: 54,
    tirePsi: [31, 31, 30, 32],
    engine: 'off',
    obd: 'disconnected',
    lastObd: '2d 14h ago',
  },
  counts: {
    openIssues: 3,
    pendingTasks: 4,
    trackedParts: 3,
    trips: 127,
    logsThisWeek: 18,
  },
  notes: [
    {
      id: 'n1',
      kind: 'ISSUE',
      title: 'Ticket light switch appears faulty',
      body: 'Switch intermittently fails to energize the lamp. Try a direct 12V test at pin 4.',
      when: 'Apr 6, 10:48 PM',
      priority: 'high',
    },
    {
      id: 'n2',
      kind: 'MAINTENANCE',
      title: 'Check AC behavior on hot day',
      body: 'Need a repeatable test when ambient temps are above 85F.',
      when: 'Apr 5, 10:48 PM',
      priority: 'med',
    },
    {
      id: 'n3',
      kind: 'ISSUE',
      title: 'Front suspension noise, passenger side',
      body: 'Noise is most noticeable over broken pavement and low-speed turns.',
      when: 'Apr 3, 10:48 PM',
      priority: 'med',
    },
    {
      id: 'n4',
      kind: 'ISSUE',
      title: 'Rear brakes need pads',
      body: 'Rotors look OK. Pads are near 15 percent.',
      when: 'Apr 2, 8:12 PM',
      priority: 'high',
    },
    {
      id: 'n5',
      kind: 'TRIP',
      title: 'Ellensburg run, I-90',
      body: 'Burned 0.6 gal more than last trip at same speed. Check tire PSI.',
      when: 'Apr 1, 6:30 PM',
      priority: 'low',
    },
  ],
  tasks: [
    {
      id: 't1',
      title: 'Order dome light LED replacements',
      detail: 'Confirm bulb type, 194 versus 168, before ordering.',
      due: 'Apr 7, 10:48 PM',
      priority: 'high',
      tag: 'PARTS',
    },
    {
      id: 't2',
      title: 'Replace rear brakes',
      detail: 'Pads and hardware checked together. Block 2 hr.',
      due: 'Apr 8, 10:48 PM',
      priority: 'high',
      tag: 'SERVICE',
    },
    {
      id: 't3',
      title: 'Inspect dome light ground',
      detail: 'Possible root cause for intermittent switch.',
      due: 'Apr 10, 9:00 AM',
      priority: 'med',
      tag: 'DIAG',
    },
    {
      id: 't4',
      title: 'Log fuel economy baseline',
      detail: 'Three consecutive fills at same station.',
      due: 'Apr 14',
      priority: 'low',
      tag: 'DATA',
    },
  ],
  parts: [
    {
      id: 'p1',
      name: 'Front brake pads, ceramic',
      status: 'ON-ORDER',
      vendor: 'RockAuto',
      eta: 'Apr 9',
      cost: 42.18,
    },
    {
      id: 'p2',
      name: 'Dome light LED, 194',
      status: 'PLANNED',
      vendor: 'Amazon',
      eta: 'TBD',
      cost: 8.99,
    },
    {
      id: 'p3',
      name: 'Power steering fluid',
      status: 'IN-STOCK',
      vendor: 'Autozone',
      eta: 'now',
      cost: 6.49,
    },
  ],
  transcript: [
    { who: 'vic', text: 'Standing by.', t: '04:27' },
    { who: 'driver', text: 'status report', t: '04:26' },
    { who: 'vic', text: '3 open issues. 4 tasks. Rear brakes and dome light both overdue.', t: '04:26' },
    { who: 'driver', text: 'log: dome light flickers on bumps', t: '04:25' },
    { who: 'vic', text: 'Logged. Linked to existing dome-light switch ticket.', t: '04:25' },
    { who: 'vic', text: 'Probable cause: ground strap on cargo lamp harness.', t: '04:25' },
  ],
  eventLog: [
    { t: '04:28:02', tag: 'SYS', text: 'Mic hotword detected / confidence 0.92' },
    { t: '04:27:41', tag: 'NET', text: 'Socket handshake to assistant-core OK' },
    { t: '04:26:10', tag: 'DATA', text: 'Vehicle state snapshot written / 2.1 KB' },
    { t: '04:25:33', tag: 'TOOL', text: 'log_vehicle_issue() -> ticket#0482' },
    { t: '04:25:30', tag: 'VOICE', text: 'Driver utterance captured / 3.8s' },
    { t: '04:24:14', tag: 'OBD', text: 'Adapter not responding / retry 3/3' },
    { t: '04:24:08', tag: 'OBD', text: 'Adapter disconnected / fallback active' },
    { t: '04:23:01', tag: 'SYS', text: 'Motion state: parked / idle 12m' },
  ],
  modes: [
    { id: 'driving', label: 'DRIVING', glyph: '01' },
    { id: 'nav', label: 'NAV', glyph: '02' },
    { id: 'parked', label: 'PARKED', glyph: '03' },
    { id: 'diagnostics', label: 'DIAGNOSTICS', glyph: '04' },
    { id: 'system', label: 'SYSTEM', glyph: '05' },
    { id: 'ambient', label: 'AMBIENT', glyph: '06' },
  ],
  quickActions: [
    { id: 'log', label: 'LOG ISSUE', icon: 'alert', hotkey: 'L' },
    { id: 'remind', label: 'REMINDER', icon: 'bell', hotkey: 'R' },
    { id: 'notes', label: 'NOTES', icon: 'file', hotkey: 'N' },
    { id: 'parts', label: 'PARTS', icon: 'box', hotkey: 'P' },
    { id: 'diag', label: 'DIAGNOSTICS', icon: 'gauge', hotkey: 'D' },
    { id: 'nav', label: 'NAVIGATE', icon: 'nav', hotkey: 'G' },
  ],
};

export function useVicMockData(): VicData {
  return useMemo(() => VIC_MOCK_DATA, []);
}
